config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users
  resources :products
  root "products#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  scope :get_parents, -> {where(parent_id: nil)}
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  has_many :products
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  scope :get_admin, -> {where(admin: true)}
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def check_admin
    redirect_to root_url unless current_user && current_user.admin?
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys:[:name,:lastname,:phone,:gender,:age])
    devise_parameter_sanitizer.permit(:sign_up, keys:[:name,:lastname,:phone,:gender,:age])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :find_category, only: [:show,:destroy,:edit,:update]
    before_action :check_admin, only: [:show,:index,:edit,:destroy,:new]

  def index
      @categories = Category.all.order("created_at DESC")
  end
  def new
        @category = Category.new
  end

  def create
      @category = Category.new(category_params)
      if @category.save
        redirect_to root_path
      else
        render 'new'
      end
  end
  def show
  end
  def edit
  end

  def update

  end

  def destroy

  end
  private
   def category_params
     params.require(:category).permit(:title,:parent_id)
   end
   def find_category
       @category = Category.find(params[:id])
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :find_product, only: [:show,:destroy,:edit,:update]
  before_action :check_admin, only: [:edit,:new]
  def index
    if params[:category].blank?
      @products = Product.all.order('created_at DESC')
    else
      @category_id = Category.find_by(title: params[:category]).id
      @products = Product.where(:category_id => @category_id).order("created_at DESC")
    end
  end
  def new
        @product = Product.new
    end

  def create
      @product = Product.new(product_params)
      if @product.save
        redirect_to root_path
      else
        render 'new'
      end
  end

  def show
    # @product = Product.find(params[:id])
  end
  def edit
  end
  def update
    if @product.update(product_params)
      redirect_to product_path(@product)
    else
      render 'edit'
    end
  end

  def destroy
    @product.destroy
    redirect_to root_path
  end
  private
   def product_params
     params.require(:product).permit(:title,:description,:price,:discount,:available, :category_id,:image)
   end
   def find_product
       @product = Product.find(params[:id])
   end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_fromcat.html.erb
<%= simple_form_for @category,:html => {:multipart => true} do |f|%>
  <%= f.input :title, label: "Category Title",required:true%>
  <%= f.input :parent_id %>
  <%= f.button :submit %>
<% end %>

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/edit.html.erb
<h1>Categories#edit</h1>
<p>Find me in app/views/categories/edit.html.erb</p>

app/views/categories/index.html.erb
<div class="container">
  <h1>Categories#index</h1>
  <% @categories.each do |category|%>
    <p> id: <%= category.id%>
    <%= category.title %>
    <%= category.parent_id %>
    </p>
  <% end %>
</div>

app/views/categories/new.html.erb
<div class="container"><h1>New Category </h1>
<%= render 'fromcat'%>
</div>

app/views/categories/show.html.erb
<%= @category.title %>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Alte.Do The Sport</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button"class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
            <%= link_to "Store name", root_path ,class:"navbar-brand"%>
        </div>

        <div class="collapse navbar-collapse" id ="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <% if current_user && current_user.admin? %>
            <li>
            <%= link_to "Add category", new_category_path(@categories), class:'navbar-link'%>
            </li>
            <% end %>
          </ul>
          <ul class="nav navbar-nav navbar-right">

            <% if user_signed_in?%>
            Logged in as <strong><%= current_user.email %></strong>.
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-brand' %>
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-brand'  %>
            <% else %>
            <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-brand'  %>
            <%= link_to "Login", new_user_session_path, :class => 'navbar-brand'  %>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= simple_form_for @product,:html => {:multipart => true} do |f|%>
  <%= f.input :title, label: "Product Title"%>
  <%= f.input :description %>
  <%= f.input :price %>
  <%= f.input :discount %>
  <%= f.input :available %>
  <%= f.input :category_id, collection: Category.get_parents ,placeholder:"sds"%>
  <%= f.file_field :image, as: :file%>
  <%= f.button :submit %>
<% end %>

app/views/products/edit.html.erb
<h1>Edit Page</h1>
<% if @product.errors.any?%>
  <% @product.errors.full_messages.each do |m|%>
  <h2> <%= m%> </h2>
  <%end%>
<%end%>
<%= render 'form'%>

app/views/products/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-3">
        <hr>
        <h3 class="font-weight-bold">
          <strong >SHOP</strong>
        </h3>
        <hr>
        <ul class="nav nav-navbar nav-stacked">
          <li class="active"><a href="products#index">All Products</a></li>
          <li class="dropdown">
            <% Category.get_parents.each do |category| %>

                <%= link_to category.title, products_path(category: category.title),class:"link"%>

              <% end %>

          </li>
        </ul>
    </div>

    <div class="col-sm-9">
      <div class="row">
        <h1 >
          <strong>
            All Products
          </strong>
        </h1>
      </div>
      <div class="">
        <% if current_user && current_user.admin? %>
          <%= link_to "Add product", new_product_path(@products)%>
        <% end %>
      </div>
      <% @products.each do |product| %>
        <div class="col-xs-6 col-sm-4">

            <div class="thumbnail">
              <a  class = "" href = "<%= product_path(product)%>">
              <img src="<%= product.image %>" alt="Product" style="width:100%">
              <div class="caption">
                <h3><%= product.title%></h3>
                <div class="row">
                  <% if product.discount!=0 %>
                    <div class="col-sm-6">
                      $ <del><%= product.price%></del>
                      <strong>$ <%= product.price-(product.price*product.discount)/100.0%></strong>
                    </div>
                    <div class="col-sm-6">

                      Discount: <%= product.discount%>%

                    </div>
                  <% else %>
                  <strong>
                    <div class="col-sm-12">
                      $ <%= product.price %>
                    </div>
                  </strong>
                  <% end %>
                </div>
              </div>
            </div>
          </a>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/products/new.html.erb
<% if @product.errors.any?%>
  <% @product.errors.full_messages.each do |m|%>
  <h2> <%= m%> </h2>
  <%end%>
<%end%>

<div class="container"><h1>New Product</h1>
<%= render 'form'%>
</div>

app/views/products/show.html.erb
<img src="<%= @product.image%>" alt="">
<h2><%= @product.title %></h2>
<p><%= @product.description %></p>
<p><%= @product.price %></p>
<p><%= @product.discount %></p>
<p><%= @product.available %></p>
<p><%= @product.category_id %></p>
<%= link_to "Back", root_path%>
<% if current_user && current_user.admin? %>
  <%= link_to "Edit", edit_product_path(@product)%>
  <%= link_to "Delete", product_path(@product), method: :delete, data: {confirm:"Are you sure?"}%>
<% end %>